// <auto-generated />
using System;

namespace MyLanguageLearningApp
{
    // This class is automatically generated by the Xamarin.Android build process.
    public static class Resource
    {
        public static class Attribute
        {
        }

        public static class Drawable
        {
            public const int Icon = 2130837504;
        }

        public static class Id
        {
            public const int add_button = 2131165192;
            public const int translation_edit_text = 2131165301;
            public const int word_edit_text = 2131165302;
            public const int word_list_view = 2131165303;
        }

        public static class Layout
        {
            public const int Main = 2131230720;
        }

        public static class String
        {
            public const int app_name = 2131296256;
            public const int hello = 2131296257;
        }
    }
}
